# -*- coding: utf-8 -*-
"""Mission Review

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2X106grpPKJhW2tB8OliL5WCaRacDpQ
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from io import BytesIO

# =====================
# PAGE CONFIG
# =====================

st.set_page_config(
    page_title="Mission Review",
    layout="wide"
)

st.title("📊 Mission Review")

# =====================
# UPLOAD FILE
# =====================

uploaded_file = st.file_uploader(
    "Upload Excel / CSV",
    type=["xlsx","csv"]
)

if uploaded_file:

    # READ FILE
    if uploaded_file.name.endswith(".xlsx"):
        df = pd.read_excel(uploaded_file)
    else:
        df = pd.read_csv(uploaded_file)

    st.success("File berhasil diupload!")

    # =====================
    # DATA CLEANING
    # =====================

    df['Submit'] = (
        df['Submit']
        .fillna('No')
        .astype(str)
        .str.strip()
    )

    # =====================
    # SUMMARY TABLE
    # =====================

    summary = (
        df.groupby(
            ['Cycle','Activity','Submit']
        )
        .size()
        .unstack(fill_value=0)
        .reset_index()
    )

    if 'Yes' not in summary.columns:
        summary['Yes'] = 0

    if 'No' not in summary.columns:
        summary['No'] = 0

    summary = summary.rename(columns={
        'Yes':'Jumlah Submit',
        'No':'Jumlah No Submit'
    })

    # =====================
    # SIDEBAR FILTER
    # =====================

    st.sidebar.header("Filter")

    cycle_list = (
        ['All']
        + list(summary['Cycle'].unique())
    )

    selected_cycle = st.sidebar.selectbox(
        "Pilih Cycle",
        cycle_list
    )

    filtered = summary.copy()

    if selected_cycle != 'All':

        filtered = filtered[
            filtered['Cycle']
            == selected_cycle
        ]

    # =====================
    # KPI CARD
    # =====================

    total_submit = filtered[
        'Jumlah Submit'
    ].sum()

    total_no_submit = filtered[
        'Jumlah No Submit'
    ].sum()

    total_activity = filtered[
        'Activity'
    ].nunique()

    col1,col2,col3 = st.columns(3)

    col1.metric(
        "Total Submit",
        f"{total_submit:,}"
    )

    col2.metric(
        "Total No Submit",
        f"{total_no_submit:,}"
    )

    col3.metric(
        "Total Activity",
        f"{total_activity:,}"
    )

    # =====================
    # TABLE
    # =====================

    st.subheader("📋 Pengerjaan Mission")

    st.dataframe(
        filtered,
        use_container_width=True
    )

    # =====================
    # RANKING
    # =====================

    ranking = filtered.sort_values(
        by='Jumlah No Submit',
        ascending=False
    )

    st.subheader(
        "🏆 Task & Activity Tidak Submit"
    )

    st.dataframe(
        ranking[
            [
                'Cycle',
                'Task',
                'Activity',
                'Jumlah No Submit'
            ]
        ],
        use_container_width=True
    )

    # =====================
    # DOWNLOAD SUMMARY
    # =====================

    excel_file = BytesIO()

    with pd.ExcelWriter(
        excel_file,
        engine='openpyxl'
    ) as writer:

        filtered.to_excel(
            writer,
            index=False
        )

    st.download_button(
        label="⬇ Download Summary Excel",
        data=excel_file.getvalue(),
        file_name='summary.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )

else:

    st.info(
        "Silakan upload file Excel atau CSV."
    )
